### ISSUE TITLE
No Proposal Provided

### ISSUE THREAD

**Issue by jasonseminara** [meilani/final_project#1]
Please provide your proposal ASAP.

**Comment by meilani** [comment]
Sorry, it wasn't in master branch before. Or is it too short?

**Comment by jasonseminara** [comment]
It's not clear what the application is. Please be more verbose and pitch your idea like I'm an investor or a stakeholder in some way.

**Comment by meilani** [comment]
updated

**Comment by jasonseminara** [comment]
Great! approved.
